### PR TITLE
global config/mongodb

### PR DESCRIPTION
**Pull request by mschwartz**
remove Config.js and use MQTT to fetch client configuration.

### CODE REVIEW

**Comment by mschwartz** [comment]
THIS IS IN PROGRESS, DO NOT MERGE.
@grgur

**Comment by mschwartz** [comment]
ready for merge, @grgur

**Comment by mschwartz** [comment]
@grgur this was blocking me, so I merged it.

You can still review it and submit a PR to fix anything you don't like that I did...

**Comment by grgur** [comment]
Thanks for merging it @mschwartz

**Pull request merged**
