### PR TITLE
Ionic tab navigation

### PR DESCRIPTION
**Pull request by grgur**
image

This is the first Ionic migration. Ionic tabs require React Router that I implemented with browser history. Our custom secondary navigation memoization is kept alive.

The app has freed up some memory (great for Androids) and the bundles are much smaller

```sh
23.24 KB (-59.98 KB)  build/static/js/11.90afc848.chunk.js
2.32 KB (-73.38 KB)   build/static/js/0.352b5a06.chunk.js
1.68 KB (-20.62 KB)   build/static/js/tablet.90b46c63.chunk.js
341 B (-90.93 KB)     build/static/js/10.e3071252.chunk.js
```

The icons have changed a bit and branding has been lost. I don't think we'll keep the tabs in this place, anyway.

### CODE REVIEW

**Comment by mschwartz** [comment]
The top tabs are too tall.  You have wasted space on the bottom where the main screen in my setup has room for another row of tiles.

2019-06-26 at 11 43 AM

**Comment by mschwartz** [comment]
Maybe I'm not seeing the whole screen in your screenshot...

**Comment by mschwartz** [comment]
The branding was a "reset" app link.  It should also clear localStorage() - it might not be doing that currently, but it should.

**Comment by grgur** [comment]
> The top tabs are too tall. You have wasted space on the bottom where the main screen in my setup has room for another row of tiles.

It's just how I cut the screenshot. 

> The branding was a "reset" app link. It should also clear localStorage() - it might not be doing that currently, but it should.

The only thing that persists right now is secondary navigation level. That's something we need to revisit anyway.

**Pull request merged**
