### PR TITLE
MQTT provider

### LINKED ISSUE #19: Decouple MQTT into a provider
Provide context to the rest of the app

### PR DESCRIPTION
**Pull request by grgur**
MQTT provider adds context data for the MQTT service. It also allows the app to be started without having to wait for the MQTT connection

Ideally, we could use the MQTT service via a hook, but that's out of scope for this PR

Closes #19

### CODE REVIEW

**Comment by grgur** [comment]
@mschwartz there's a chance that a subscription could be registered before the connection was made. I assume MQTT handled that internally. If not, we'll have to queue them up and re-register on connection

**Comment by mschwartz** [comment]
> @mschwartz there's a chance that a subscription could be registered before the connection was made. I assume MQTT handled that internally. If not, we'll have to queue them up and re-register on connection

I don't know of MQTT handles this internally.  The @/lib/MQTT.js I wrote does not, but it wraps a 3rd party MQTT client, so who knows?

I also tried a useMQTT strategy before and scrapped it.

**Comment by mschwartz** [comment]
Forgive my ignorance on this one...

Why is 
```
const MQTT = useMQTT();
```

better than

```
import MQTT from "@/lib/MQTT";
```

?

**Comment by grgur** [comment]
@mschwartz ideally you wouldn't create a class just to instantiate it once, right? Technically, we should instantiate it separately from the class definition. Couldn't the users choose to use their own Mqtt service for something else?

The hook is there, but it's not used at the moment. Should we decouple the mqtt instance from the class definition then we would need to store the instance somewhere. Context is often the place where react apps store such a thing (e.g. React Router, Redux, and many others). Accessing context via hooks is perhaps a tiny bit cleaner.

The one thing I want to solve with this PR is to let the app load instead of having to wait for the mqtt  connection to be established before it's rendered.

**Comment by mschwartz** [comment]
MQTT is a singleton.  There's nothing wrong with that...

The reason it did wait for MQTT connection is because subscriptions do occur as soon as the first component's useEffect is called.

**Comment by mschwartz** [comment]
> Closes #19

I love this, BTW.  It is the RIGHT way to use GitHub issues!

**Comment by grgur** [comment]
> The reason it did wait for MQTT connection is because subscriptions do occur as soon as the first component's useEffect is called.

Looks like subscriptions are queued properly. Let's not keep the app from loading, even if connections are quick. There's a lot to download.

**Pull request merged**
